# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 00:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_prices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prices',
            old_name='high_price',
            new_name='last_price',
        ),
        migrations.RemoveField(
            model_name='prices',
            name='min_price',
        ),
    ]
